// СГЕНЕРИРОВАНО `python3 tools/gen_keysym.py` — НЕ РЕДАКТИРОВАТЬ ВРУЧНУЮ.
//
// Имена клавиш (E_SONO_KEY -> строка), извлечённые из бинарника-референса
// update/root/X2000, класс KKey2Name (platform/.../KKey2Name.cpp).
//
// В оригинале KKey2Name::GetNameOfKey КАЖДЫЙ ВЫЗОВ пересобирает эту таблицу
// на стеке (кадр 24 КБ, 614 записей) и линейно ищет по ней. Мы храним её как
// статические данные; поведение при промахе воспроизведено ("SONO_Unknown").
#pragma once

#include <string>

namespace keyname {

struct stKeyName { int eKey; const char* pszName; };

// 614 записей; порядок — как в референсе (важен: возможны дубли кодов,
// линейный поиск возвращает ПЕРВОЕ совпадение).
inline const stKeyName g_astKeyName[614] = {
    { 0x0000, "PADK_UNKNOWN" },
    { 0x0000, "PADK_FIRST" },
    { 0x0008, "PADK_BACKSPACE" },
    { 0x0009, "PADK_TAB" },
    { 0x000c, "PADK_CLEAR" },
    { 0x000d, "PADK_RETURN" },
    { 0x0013, "PADK_PAUSE" },
    { 0x001b, "PADK_ESCAPE" },
    { 0x0020, "PADK_SPACE" },
    { 0x0021, "PADK_EXCLAIM" },
    { 0x0022, "PADK_QUOTEDBL" },
    { 0x0023, "PADK_HASH" },
    { 0x0024, "PADK_DOLLAR" },
    { 0x0026, "PADK_AMPERSAND" },
    { 0x0027, "PADK_QUOTE" },
    { 0x0028, "PADK_LEFTPAREN" },
    { 0x0029, "PADK_RIGHTPAREN" },
    { 0x002a, "PADK_ASTERISK" },
    { 0x002b, "PADK_PLUS" },
    { 0x002c, "PADK_COMMA" },
    { 0x002d, "PADK_MINUS" },
    { 0x002e, "PADK_PERIOD" },
    { 0x002f, "PADK_SLASH" },
    { 0x0030, "PADK_0" },
    { 0x0031, "PADK_1" },
    { 0x0032, "PADK_2" },
    { 0x0033, "PADK_3" },
    { 0x0034, "PADK_4" },
    { 0x0035, "PADK_5" },
    { 0x0036, "PADK_6" },
    { 0x0037, "PADK_7" },
    { 0x0038, "PADK_8" },
    { 0x0039, "PADK_9" },
    { 0x003a, "PADK_COLON" },
    { 0x003b, "PADK_SEMICOLON" },
    { 0x003c, "PADK_LESS" },
    { 0x003d, "PADK_EQUALS" },
    { 0x003e, "PADK_GREATER" },
    { 0x003f, "PADK_QUESTION" },
    { 0x0040, "PADK_AT" },
    { 0x005b, "PADK_LEFTBRACKET" },
    { 0x005c, "PADK_BACKSLASH" },
    { 0x005d, "PADK_RIGHTBRACKET" },
    { 0x005e, "PADK_CARET" },
    { 0x005f, "PADK_UNDERSCORE" },
    { 0x0060, "PADK_BACKQUOTE" },
    { 0x0061, "PADK_a" },
    { 0x0062, "PADK_b" },
    { 0x0063, "PADK_c" },
    { 0x0064, "PADK_d" },
    { 0x0065, "PADK_e" },
    { 0x0066, "PADK_f" },
    { 0x0067, "PADK_g" },
    { 0x0068, "PADK_h" },
    { 0x0069, "PADK_i" },
    { 0x006a, "PADK_j" },
    { 0x006b, "PADK_k" },
    { 0x006c, "PADK_l" },
    { 0x006d, "PADK_m" },
    { 0x006e, "PADK_n" },
    { 0x006f, "PADK_o" },
    { 0x0070, "PADK_p" },
    { 0x0071, "PADK_q" },
    { 0x0072, "PADK_r" },
    { 0x0073, "PADK_s" },
    { 0x0074, "PADK_t" },
    { 0x0075, "PADK_u" },
    { 0x0076, "PADK_v" },
    { 0x0077, "PADK_w" },
    { 0x0078, "PADK_x" },
    { 0x0079, "PADK_y" },
    { 0x007a, "PADK_z" },
    { 0x007f, "PADK_DELETE" },
    { 0x00a0, "PADK_WORLD_0" },
    { 0x00a1, "PADK_WORLD_1" },
    { 0x00a2, "PADK_WORLD_2" },
    { 0x00a3, "PADK_WORLD_3" },
    { 0x00a4, "PADK_WORLD_4" },
    { 0x00a5, "PADK_WORLD_5" },
    { 0x00a6, "PADK_WORLD_6" },
    { 0x00a7, "PADK_WORLD_7" },
    { 0x00a8, "PADK_WORLD_8" },
    { 0x00a9, "PADK_WORLD_9" },
    { 0x00aa, "PADK_WORLD_10" },
    { 0x00ab, "PADK_WORLD_11" },
    { 0x00ac, "PADK_WORLD_12" },
    { 0x00ad, "PADK_WORLD_13" },
    { 0x00ae, "PADK_WORLD_14" },
    { 0x00af, "PADK_WORLD_15" },
    { 0x00b0, "PADK_WORLD_16" },
    { 0x00b1, "PADK_WORLD_17" },
    { 0x00b2, "PADK_WORLD_18" },
    { 0x00b3, "PADK_WORLD_19" },
    { 0x00b4, "PADK_WORLD_20" },
    { 0x00b5, "PADK_WORLD_21" },
    { 0x00b6, "PADK_WORLD_22" },
    { 0x00b7, "PADK_WORLD_23" },
    { 0x00b8, "PADK_WORLD_24" },
    { 0x00b9, "PADK_WORLD_25" },
    { 0x00ba, "PADK_WORLD_26" },
    { 0x00bb, "PADK_WORLD_27" },
    { 0x00bc, "PADK_WORLD_28" },
    { 0x00bd, "PADK_WORLD_29" },
    { 0x00be, "PADK_WORLD_30" },
    { 0x00bf, "PADK_WORLD_31" },
    { 0x00c0, "PADK_WORLD_32" },
    { 0x00c1, "PADK_WORLD_33" },
    { 0x00c2, "PADK_WORLD_34" },
    { 0x00c3, "PADK_WORLD_35" },
    { 0x00c4, "PADK_WORLD_36" },
    { 0x00c5, "PADK_WORLD_37" },
    { 0x00c6, "PADK_WORLD_38" },
    { 0x00c7, "PADK_WORLD_39" },
    { 0x00c8, "PADK_WORLD_40" },
    { 0x00c9, "PADK_WORLD_41" },
    { 0x00ca, "PADK_WORLD_42" },
    { 0x00cb, "PADK_WORLD_43" },
    { 0x00cc, "PADK_WORLD_44" },
    { 0x00cd, "PADK_WORLD_45" },
    { 0x00ce, "PADK_WORLD_46" },
    { 0x00cf, "PADK_WORLD_47" },
    { 0x00d0, "PADK_WORLD_48" },
    { 0x00d1, "PADK_WORLD_49" },
    { 0x00d2, "PADK_WORLD_50" },
    { 0x00d3, "PADK_WORLD_51" },
    { 0x00d4, "PADK_WORLD_52" },
    { 0x00d5, "PADK_WORLD_53" },
    { 0x00d6, "PADK_WORLD_54" },
    { 0x00d7, "PADK_WORLD_55" },
    { 0x00d8, "PADK_WORLD_56" },
    { 0x00d9, "PADK_WORLD_57" },
    { 0x00da, "PADK_WORLD_58" },
    { 0x00db, "PADK_WORLD_59" },
    { 0x00dc, "PADK_WORLD_60" },
    { 0x00dd, "PADK_WORLD_61" },
    { 0x00de, "PADK_WORLD_62" },
    { 0x00df, "PADK_WORLD_63" },
    { 0x00e0, "PADK_WORLD_64" },
    { 0x00e1, "PADK_WORLD_65" },
    { 0x00e2, "PADK_WORLD_66" },
    { 0x00e3, "PADK_WORLD_67" },
    { 0x00e4, "PADK_WORLD_68" },
    { 0x00e5, "PADK_WORLD_69" },
    { 0x00e6, "PADK_WORLD_70" },
    { 0x00e7, "PADK_WORLD_71" },
    { 0x00e8, "PADK_WORLD_72" },
    { 0x00e9, "PADK_WORLD_73" },
    { 0x00ea, "PADK_WORLD_74" },
    { 0x00eb, "PADK_WORLD_75" },
    { 0x00ec, "PADK_WORLD_76" },
    { 0x00ed, "PADK_WORLD_77" },
    { 0x00ee, "PADK_WORLD_78" },
    { 0x00ef, "PADK_WORLD_79" },
    { 0x00f0, "PADK_WORLD_80" },
    { 0x00f1, "PADK_WORLD_81" },
    { 0x00f2, "PADK_WORLD_82" },
    { 0x00f3, "PADK_WORLD_83" },
    { 0x00f4, "PADK_WORLD_84" },
    { 0x00f5, "PADK_WORLD_85" },
    { 0x00f6, "PADK_WORLD_86" },
    { 0x00f7, "PADK_WORLD_87" },
    { 0x00f8, "PADK_WORLD_88" },
    { 0x00f9, "PADK_WORLD_89" },
    { 0x00fa, "PADK_WORLD_90" },
    { 0x00fb, "PADK_WORLD_91" },
    { 0x00fc, "PADK_WORLD_92" },
    { 0x00fd, "PADK_WORLD_93" },
    { 0x00fe, "PADK_WORLD_94" },
    { 0x00ff, "PADK_WORLD_95" },
    { 0x0100, "PADK_KP0" },
    { 0x0101, "PADK_KP1" },
    { 0x0102, "PADK_KP2" },
    { 0x0103, "PADK_KP3" },
    { 0x0104, "PADK_KP4" },
    { 0x0105, "PADK_KP5" },
    { 0x0106, "PADK_KP6" },
    { 0x0107, "PADK_KP7" },
    { 0x0108, "PADK_KP8" },
    { 0x0109, "PADK_KP9" },
    { 0x010a, "PADK_KP_PERIOD" },
    { 0x010b, "PADK_KP_DIVIDE" },
    { 0x010c, "PADK_KP_MULTIPLY" },
    { 0x010d, "PADK_KP_MINUS" },
    { 0x010e, "PADK_KP_PLUS" },
    { 0x010f, "PADK_KP_ENTER" },
    { 0x0110, "PADK_KP_EQUALS" },
    { 0x0111, "PADK_UP" },
    { 0x0112, "PADK_DOWN" },
    { 0x0113, "PADK_RIGHT" },
    { 0x0114, "PADK_LEFT" },
    { 0x0115, "PADK_INSERT" },
    { 0x0116, "PADK_HOME" },
    { 0x0117, "PADK_END" },
    { 0x0118, "PADK_PAGEUP" },
    { 0x0119, "PADK_PAGEDOWN" },
    { 0x011a, "PADK_F1" },
    { 0x011b, "PADK_F2" },
    { 0x011c, "PADK_F3" },
    { 0x011d, "PADK_F4" },
    { 0x011e, "PADK_F5" },
    { 0x011f, "PADK_F6" },
    { 0x0120, "PADK_F7" },
    { 0x0121, "PADK_F8" },
    { 0x0122, "PADK_F9" },
    { 0x0123, "PADK_F10" },
    { 0x0124, "PADK_F11" },
    { 0x0125, "PADK_F12" },
    { 0x0126, "PADK_F13" },
    { 0x0127, "PADK_F14" },
    { 0x0128, "PADK_F15" },
    { 0x012c, "PADK_NUMLOCK" },
    { 0x012d, "PADK_CAPSLOCK" },
    { 0x012e, "PADK_SCROLLOCK" },
    { 0x012f, "PADK_RSHIFT" },
    { 0x0130, "PADK_LSHIFT" },
    { 0x0131, "PADK_RCTRL" },
    { 0x0132, "PADK_LCTRL" },
    { 0x0133, "PADK_RALT" },
    { 0x0134, "PADK_LALT" },
    { 0x0135, "PADK_RMETA" },
    { 0x0136, "PADK_LMETA" },
    { 0x0137, "PADK_LSUPER" },
    { 0x0138, "PADK_RSUPER" },
    { 0x0139, "PADK_MODE" },
    { 0x013a, "PADK_COMPOSE" },
    { 0x013b, "PADK_HELP" },
    { 0x013c, "PADK_PRINT" },
    { 0x013d, "PADK_SYSREQ" },
    { 0x013e, "PADK_BREAK" },
    { 0x013f, "PADK_MENU" },
    { 0x0140, "PADK_POWER" },
    { 0x0141, "PADK_EURO" },
    { 0x0142, "PADK_UNDO" },
    { 0x03e9, "SONO_FREEZE" },
    { 0x03ea, "SONO_SaveCine" },
    { 0x03eb, "SONO_Power" },
    { 0x03ec, "SONO_PATDAT" },
    { 0x03ed, "SONO_REPORT" },
    { 0x03ee, "SONO_PROBE" },
    { 0x03ef, "SONO_ENDEXAM" },
    { 0x03f0, "SONO_REVIEW" },
    { 0x03f1, "SONO_P1" },
    { 0x03f2, "SONO_P2" },
    { 0x03f3, "SONO_ELASTRO" },
    { 0x03f4, "SONO_CONSTRAST" },
    { 0x03f5, "SONO_3D4D" },
    { 0x03f6, "SONO_ANGLE_KNOB" },
    { 0x03f7, "SONO_ANGLE" },
    { 0x03f8, "SONO_BodyMark_Knob" },
    { 0x03f9, "SONO_BodyMark" },
    { 0x03fa, "SONO_Clear" },
    { 0x03fb, "SONO_Pointer" },
    { 0x03fc, "SONO_Annot" },
    { 0x03fd, "SONO_Update" },
    { 0x03fe, "SONO_Calc" },
    { 0x03ff, "SONO_Caliper" },
    { 0x0400, "SONO_Auto" },
    { 0x0401, "SONO_Print" },
    { 0x0402, "SONO_VideoPrint" },
    { 0x0403, "SONO_SaveImage" },
    { 0x0404, "SONO_Depth_Knob" },
    { 0x0405, "SONO_Depth" },
    { 0x0406, "SONO_Zoom_Knob" },
    { 0x0407, "SONO_Zoom" },
    { 0x0408, "SONO_Scale_Up" },
    { 0x0409, "SONO_Scale_Down" },
    { 0x040a, "SONO_Baseline_Up" },
    { 0x040b, "SONO_Baseline_Down" },
    { 0x040c, "SONO_2B" },
    { 0x040d, "SONO_4B" },
    { 0x040e, "SONO_B_Mode_Knob" },
    { 0x040f, "SONO_B_Mode" },
    { 0x0410, "SONO_CFM_Mode_Knob" },
    { 0x0411, "SONO_CFM_Mode" },
    { 0x0412, "SONO_PW_Mode_Knob" },
    { 0x0413, "SONO_PW_Mode" },
    { 0x0414, "SONO_CW_Mode_Knob" },
    { 0x0415, "SONO_CW_Mode" },
    { 0x0416, "SONO_M_Mode_Knob" },
    { 0x0417, "SONO_M_Mode" },
    { 0x0418, "SONO_TouchScreen_Keyboard" },
    { 0x0419, "SONO_TouchScreen_Knob1" },
    { 0x041a, "SONO_TouchScreen_Knob2" },
    { 0x041b, "SONO_TouchScreen_Knob3" },
    { 0x041c, "SONO_TouchScreen_Knob4" },
    { 0x041d, "SONO_TouchScreen_Knob5" },
    { 0x041e, "SONO_Audio_Knob" },
    { 0x041f, "SONO_Setup" },
    { 0x0420, "SONO_Help" },
    { 0x0421, "SONO_P3" },
    { 0x0422, "SONO_P4" },
    { 0x0423, "SONO_Biopsy" },
    { 0x0424, "SONO_Panoramic" },
    { 0x0425, "SONO_PDI" },
    { 0x0426, "SONO_TDI" },
    { 0x0427, "SONO_Updown_Revert" },
    { 0x0428, "SONO_Leftright_Revert" },
    { 0x0429, "SONO_THI" },
    { 0x042a, "SONO_Invert" },
    { 0x042b, "SONO_PrintScreen" },
    { 0x042c, "SONO_Del" },
    { 0x042d, "SONO_QuoteLeft" },
    { 0x042e, "SONO_1" },
    { 0x042f, "SONO_2" },
    { 0x0430, "SONO_3" },
    { 0x0431, "SONO_4" },
    { 0x0432, "SONO_5" },
    { 0x0433, "SONO_6" },
    { 0x0434, "SONO_7" },
    { 0x0435, "SONO_8" },
    { 0x0436, "SONO_9" },
    { 0x0437, "SONO_0" },
    { 0x0438, "SONO_Minus" },
    { 0x0439, "SONO_Equal" },
    { 0x043a, "SONO_BackSpace" },
    { 0x043b, "SONO_Tab" },
    { 0x043c, "SONO_Q" },
    { 0x043d, "SONO_W" },
    { 0x043e, "SONO_E" },
    { 0x043f, "SONO_R" },
    { 0x0440, "SONO_T" },
    { 0x0441, "SONO_Y" },
    { 0x0442, "SONO_U" },
    { 0x0443, "SONO_I" },
    { 0x0444, "SONO_O" },
    { 0x0445, "SONO_P" },
    { 0x0446, "SONO_BracketLeft" },
    { 0x0447, "SONO_BracketRight" },
    { 0x0448, "SONO_BackSlash" },
    { 0x0449, "SONO_CapsLock" },
    { 0x044a, "SONO_A" },
    { 0x044b, "SONO_S" },
    { 0x044c, "SONO_D" },
    { 0x044d, "SONO_F" },
    { 0x044e, "SONO_G" },
    { 0x044f, "SONO_H" },
    { 0x0450, "SONO_J" },
    { 0x0451, "SONO_K" },
    { 0x0452, "SONO_L" },
    { 0x0453, "SONO_Semicolon" },
    { 0x0454, "SONO_QuoteRight" },
    { 0x0455, "SONO_Enter" },
    { 0x0456, "SONO_Shift_Left" },
    { 0x0457, "SONO_Z" },
    { 0x0458, "SONO_X" },
    { 0x0459, "SONO_C" },
    { 0x045a, "SONO_V" },
    { 0x045b, "SONO_B" },
    { 0x045c, "SONO_N" },
    { 0x045d, "SONO_M" },
    { 0x045e, "SONO_Comma" },
    { 0x045f, "SONO_Period" },
    { 0x0460, "SONO_Slash" },
    { 0x0461, "SONO_UpArrow" },
    { 0x0462, "SONO_Shift_Right" },
    { 0x0463, "SONO_Control_Left" },
    { 0x0464, "SONO_Function" },
    { 0x0465, "SONO_Arrow" },
    { 0x0466, "SONO_Alt" },
    { 0x0467, "SONO_Space" },
    { 0x0468, "SONO_AltGr" },
    { 0x0469, "SONO_ScreenZoom" },
    { 0x046a, "SONO_LeftArrow" },
    { 0x046b, "SONO_DownArrow" },
    { 0x046c, "SONO_RightArrow" },
    { 0x046d, "SONO_Set_Left" },
    { 0x046e, "SONO_Set_Right" },
    { 0x046f, "SONO_BackLight_Up" },
    { 0x0470, "SONO_Volumn_Down" },
    { 0x0471, "SONO_BackLight_Down" },
    { 0x0472, "SONO_Volumn_Up" },
    { 0x0473, "SONO_a" },
    { 0x0474, "SONO_aacute" },
    { 0x0475, "SONO_adiaeresis" },
    { 0x0476, "SONO_ae" },
    { 0x0477, "SONO_ampersand" },
    { 0x0478, "SONO_aring" },
    { 0x0479, "SONO_asciicircum" },
    { 0x047a, "SONO_asciitilde" },
    { 0x047b, "SONO_asterisk" },
    { 0x047c, "SONO_at" },
    { 0x047d, "SONO_b" },
    { 0x047e, "SONO_bar" },
    { 0x047f, "SONO_braceleft" },
    { 0x0480, "SONO_braceright" },
    { 0x0481, "SONO_brokenbar" },
    { 0x0482, "SONO_c" },
    { 0x0483, "SONO_ccedilla" },
    { 0x0484, "SONO_cent" },
    { 0x0485, "SONO_colon" },
    { 0x0486, "SONO_copyright" },
    { 0x0487, "SONO_currency" },
    { 0x0488, "SONO_d" },
    { 0x0489, "SONO_division" },
    { 0x048a, "SONO_dollar" },
    { 0x048b, "SONO_e" },
    { 0x048c, "SONO_eacute" },
    { 0x048d, "SONO_eth" },
    { 0x048e, "SONO_EuroSign" },
    { 0x048f, "SONO_exclam" },
    { 0x0490, "SONO_exclamdown" },
    { 0x0491, "SONO_f" },
    { 0x0492, "SONO_g" },
    { 0x0493, "SONO_gbreve" },
    { 0x0494, "SONO_greater" },
    { 0x0495, "SONO_h" },
    { 0x0496, "SONO_i" },
    { 0x0497, "SONO_iacute" },
    { 0x0498, "SONO_j" },
    { 0x0499, "SONO_k" },
    { 0x049a, "SONO_l" },
    { 0x049b, "SONO_less" },
    { 0x049c, "SONO_m" },
    { 0x049d, "SONO_mu" },
    { 0x049e, "SONO_multiply" },
    { 0x049f, "SONO_n" },
    { 0x04a0, "SONO_notsign" },
    { 0x04a1, "SONO_ntilde" },
    { 0x04a2, "SONO_numbersign" },
    { 0x04a3, "SONO_o" },
    { 0x04a4, "SONO_oacute" },
    { 0x04a5, "SONO_odiaeresis" },
    { 0x04a6, "SONO_oe" },
    { 0x04a7, "SONO_onesuperior" },
    { 0x04a8, "SONO_oslash" },
    { 0x04a9, "SONO_p" },
    { 0x04aa, "SONO_paragraph" },
    { 0x04ab, "SONO_parenleft" },
    { 0x04ac, "SONO_parenright" },
    { 0x04ad, "SONO_percent" },
    { 0x04ae, "SONO_plus" },
    { 0x04af, "SONO_q" },
    { 0x04b0, "SONO_question" },
    { 0x04b1, "SONO_questiondown" },
    { 0x04b2, "SONO_quotedbl" },
    { 0x04b3, "SONO_r" },
    { 0x04b4, "SONO_registered" },
    { 0x04b5, "SONO_s" },
    { 0x04b6, "SONO_scaron" },
    { 0x04b7, "SONO_scedilla" },
    { 0x04b8, "SONO_section" },
    { 0x04b9, "SONO_ssharp" },
    { 0x04ba, "SONO_sterling" },
    { 0x04bb, "SONO_t" },
    { 0x04bc, "SONO_thorn" },
    { 0x04bd, "SONO_threesuperior" },
    { 0x04be, "SONO_twosuperior" },
    { 0x04bf, "SONO_u" },
    { 0x04c0, "SONO_uacute" },
    { 0x04c1, "SONO_udiaeresis" },
    { 0x04c2, "SONO_underscore" },
    { 0x04c3, "SONO_v" },
    { 0x04c4, "SONO_w" },
    { 0x04c5, "SONO_x" },
    { 0x04c6, "SONO_y" },
    { 0x04c7, "SONO_ydiaeresis" },
    { 0x04c8, "SONO_yen" },
    { 0x04c9, "SONO_z" },
    { 0x04ca, "SONO_zcaron" },
    { 0x04cb, "SONO_Aacute" },
    { 0x04cc, "SONO_Adiaeresis" },
    { 0x04cd, "SONO_AE" },
    { 0x04ce, "SONO_Aring" },
    { 0x04cf, "SONO_Ccedilla" },
    { 0x04d0, "SONO_Eacute" },
    { 0x04d1, "SONO_ETH" },
    { 0x04d2, "SONO_Gbreve" },
    { 0x04d3, "SONO_Iacute" },
    { 0x04d4, "SONO_Ntilde" },
    { 0x04d5, "SONO_Oacute" },
    { 0x04d6, "SONO_Odiaeresis" },
    { 0x04d7, "SONO_OE" },
    { 0x04d8, "SONO_Oslash" },
    { 0x04d9, "SONO_Scaron" },
    { 0x04da, "SONO_Scedilla" },
    { 0x04db, "SONO_Thorn" },
    { 0x04dc, "SONO_Uacute" },
    { 0x04dd, "SONO_Udiaeresis" },
    { 0x04de, "SONO_Ydiaeresis" },
    { 0x04df, "SONO_Zcaron" },
    { 0x04e0, "SONO_Zoom_Up" },
    { 0x04e1, "SONO_Zoom_Down" },
    { 0x04e2, "SONO_agrave" },
    { 0x04e3, "SONO_acircumflex" },
    { 0x04e4, "SONO_atilde" },
    { 0x04e5, "SONO_Agrave" },
    { 0x04e6, "SONO_Acircumflex" },
    { 0x04e7, "SONO_Atilde" },
    { 0x04e8, "SONO_egrave" },
    { 0x04e9, "SONO_ecircumflex" },
    { 0x04ea, "SONO_etilde" },
    { 0x04eb, "SONO_ediaeresis" },
    { 0x04ec, "SONO_Egrave" },
    { 0x04ed, "SONO_Ecircumflex" },
    { 0x04ee, "SONO_Etilde" },
    { 0x04ef, "SONO_Ediaeresis" },
    { 0x04f0, "SONO_igrave" },
    { 0x04f1, "SONO_icircumflex" },
    { 0x04f2, "SONO_itilde" },
    { 0x04f3, "SONO_idiaeresis" },
    { 0x04f4, "SONO_Igrave" },
    { 0x04f5, "SONO_Icircumflex" },
    { 0x04f6, "SONO_Itilde" },
    { 0x04f7, "SONO_Idiaeresis" },
    { 0x04f8, "SONO_ograve" },
    { 0x04f9, "SONO_ocircumflex" },
    { 0x04fa, "SONO_otilde" },
    { 0x04fb, "SONO_Ograve" },
    { 0x04fc, "SONO_Ocircumflex" },
    { 0x04fd, "SONO_Otilde" },
    { 0x04fe, "SONO_ugrave" },
    { 0x04ff, "SONO_ucircumflex" },
    { 0x0500, "SONO_utilde" },
    { 0x0501, "SONO_Ugrave" },
    { 0x0502, "SONO_Ucircumflex" },
    { 0x0503, "SONO_Utilde" },
    { 0x0504, "SONO_uni2035" },
    { 0x0505, "SONO_minutes" },
    { 0x0506, "SONO_guillemotleft" },
    { 0x0507, "SONO_guillemotright" },
    { 0x0508, "SONO_degree" },
    { 0x0509, "SONO_FootSwitch_Left" },
    { 0x050a, "SONO_FootSwitch_Right" },
    { 0x050b, "SONO_Cyrillic_io" },
    { 0x050c, "SONO_Cyrillic_IO" },
    { 0x050d, "SONO_Cyrillic_numbersign" },
    { 0x050e, "SONO_Cyrillic_shorti" },
    { 0x050f, "SONO_Cyrillic_SHORTI" },
    { 0x0510, "SONO_Cyrillic_tse" },
    { 0x0511, "SONO_Cyrillic_TSE" },
    { 0x0512, "SONO_Cyrillic_u" },
    { 0x0513, "SONO_Cyrillic_U" },
    { 0x0514, "SONO_Cyrillic_ka" },
    { 0x0515, "SONO_Cyrillic_KA" },
    { 0x0516, "SONO_Cyrillic_ie" },
    { 0x0517, "SONO_Cyrillic_IE" },
    { 0x0518, "SONO_Cyrillic_en" },
    { 0x0519, "SONO_Cyrillic_EN" },
    { 0x051a, "SONO_Cyrillic_ghe" },
    { 0x051b, "SONO_Cyrillic_GHE" },
    { 0x051c, "SONO_Cyrillic_sha" },
    { 0x051d, "SONO_Cyrillic_SHA" },
    { 0x051e, "SONO_Cyrillic_shcha" },
    { 0x051f, "SONO_Cyrillic_SHCHA" },
    { 0x0520, "SONO_Cyrillic_ze" },
    { 0x0521, "SONO_Cyrillic_ZE" },
    { 0x0522, "SONO_Cyrillic_ha" },
    { 0x0523, "SONO_Cyrillic_HA" },
    { 0x0524, "SONO_Cyrillic_be" },
    { 0x0525, "SONO_Cyrillic_BE" },
    { 0x0526, "SONO_uniFE41" },
    { 0x0527, "SONO_Cyrillic_ef" },
    { 0x0528, "SONO_Cyrillic_EF" },
    { 0x0529, "SONO_Cyrillic_yeru" },
    { 0x052a, "SONO_Cyrillic_YERU" },
    { 0x052b, "SONO_Cyrillic_ve" },
    { 0x052c, "SONO_Cyrillic_VE" },
    { 0x052d, "SONO_Cyrillic_a" },
    { 0x052e, "SONO_Cyrillic_A" },
    { 0x052f, "SONO_Cyrillic_pe" },
    { 0x0530, "SONO_Cyrillic_PE" },
    { 0x0531, "SONO_Cyrillic_er" },
    { 0x0532, "SONO_Cyrillic_ER" },
    { 0x0533, "SONO_Cyrillic_o" },
    { 0x0534, "SONO_Cyrillic_O" },
    { 0x0535, "SONO_Cyrillic_el" },
    { 0x0536, "SONO_Cyrillic_EL" },
    { 0x0537, "SONO_Cyrillic_de" },
    { 0x0538, "SONO_Cyrillic_DE" },
    { 0x0539, "SONO_Cyrillic_zhe" },
    { 0x053a, "SONO_Cyrillic_ZHE" },
    { 0x053b, "SONO_Cyrillic_e" },
    { 0x053c, "SONO_Cyrillic_E" },
    { 0x053d, "SONO_Cyrillic_ya" },
    { 0x053e, "SONO_Cyrillic_YA" },
    { 0x053f, "SONO_Cyrillic_che" },
    { 0x0540, "SONO_Cyrillic_CHE" },
    { 0x0541, "SONO_Cyrillic_es" },
    { 0x0542, "SONO_Cyrillic_ES" },
    { 0x0543, "SONO_Cyrillic_em" },
    { 0x0544, "SONO_Cyrillic_EM" },
    { 0x0545, "SONO_Cyrillic_i" },
    { 0x0546, "SONO_Cyrillic_I" },
    { 0x0547, "SONO_Cyrillic_te" },
    { 0x0548, "SONO_Cyrillic_TE" },
    { 0x0549, "SONO_Cyrillic_softsign" },
    { 0x054a, "SONO_Cyrillic_SOFTSIGN" },
    { 0x054b, "SONO_Cyrillic_yu" },
    { 0x054c, "SONO_Cyrillic_YU" },
    { 0x054d, "SONO_Cyrillic_hardsign" },
    { 0x054e, "SONO_Cyrillic_HARDSIGN" },
    { 0x054f, "SONO_QuoteLeft_NoCombine" },
    { 0x0550, "SONO_QuoteRight_NoCombine" },
    { 0x0551, "SONO_asciicircum_NoCombine" },
    { 0x0552, "SONO_asciitilde_NoCombine" },
    { 0x0553, "SONO_quotedbl_NoCombine" },
    { 0x0554, "SONO_uni00A8" },
    { 0x0555, "SONO_uni2019" },
    { 0x0556, "SONO_uni015B" },
    { 0x0557, "SONO_uni017C" },
    { 0x0558, "SONO_uni02DB" },
    { 0x0559, "SONO_uni0105" },
    { 0x055a, "SONO_uni0142" },
    { 0x055b, "SONO_uni0141" },
    { 0x055c, "SONO_uni0119" },
    { 0x055d, "SONO_uni2022" },
    { 0x055e, "SONO_uni201D" },
    { 0x055f, "SONO_uni0107" },
    { 0x0560, "SONO_uni017A" },
    { 0x0561, "SONO_uni0144" },
    { 0x0562, "SONO_uni0150" },
    { 0x0563, "SONO_uni0151" },
    { 0x0564, "SONO_uni0170" },
    { 0x0565, "SONO_uni0171" },
};

// KKey2Name::GetNameOfKey: линейный поиск, при промахе — "SONO_Unknown"
// (.rodata @0x89e5d0, ветка 0x77d0d4).
inline std::string GetNameOfKey(int eKey)
{
    for (const stKeyName& st : g_astKeyName)
        if (st.eKey == eKey) return st.pszName;
    return "SONO_Unknown";
}

// 54 записей: Qt-скан-код -> имя (реф. .bss @0x14e6ba0).
inline const stKeyName g_astQtScancodeName[54] = {
    { 0x0031, "Qt_Scancode_QuoteLeft       " },
    { 0x000a, "Qt_Scancode_1               " },
    { 0x000b, "Qt_Scancode_2               " },
    { 0x000c, "Qt_Scancode_3               " },
    { 0x000d, "Qt_Scancode_4               " },
    { 0x000e, "Qt_Scancode_5               " },
    { 0x000f, "Qt_Scancode_6               " },
    { 0x0010, "Qt_Scancode_7               " },
    { 0x0011, "Qt_Scancode_8               " },
    { 0x0012, "Qt_Scancode_9               " },
    { 0x0013, "Qt_Scancode_0               " },
    { 0x0014, "Qt_Scancode_Minus           " },
    { 0x0015, "Qt_Scancode_Equal           " },
    { 0x0016, "Qt_Scancode_Backspace       " },
    { 0x0018, "Qt_Scancode_Q               " },
    { 0x0019, "Qt_Scancode_W               " },
    { 0x001a, "Qt_Scancode_E               " },
    { 0x001b, "Qt_Scancode_R               " },
    { 0x001c, "Qt_Scancode_T               " },
    { 0x001d, "Qt_Scancode_Y               " },
    { 0x001e, "Qt_Scancode_U               " },
    { 0x001f, "Qt_Scancode_I               " },
    { 0x0020, "Qt_Scancode_O               " },
    { 0x0021, "Qt_Scancode_P               " },
    { 0x0022, "Qt_Scancode_BracketLeft     " },
    { 0x0023, "Qt_Scancode_BracketRight    " },
    { 0x0033, "Qt_Scancode_Backslash       " },
    { 0x0042, "Qt_Scancode_CapsLock        " },
    { 0x0026, "Qt_Scancode_A               " },
    { 0x0027, "Qt_Scancode_S               " },
    { 0x0028, "Qt_Scancode_D               " },
    { 0x0029, "Qt_Scancode_F               " },
    { 0x002a, "Qt_Scancode_G               " },
    { 0x002b, "Qt_Scancode_H               " },
    { 0x002c, "Qt_Scancode_J               " },
    { 0x002d, "Qt_Scancode_K               " },
    { 0x002e, "Qt_Scancode_L               " },
    { 0x002f, "Qt_Scancode_Semicolon       " },
    { 0x0030, "Qt_Scancode_Apostrophe      " },
    { 0x0024, "Qt_Scancode_Return          " },
    { 0x0034, "Qt_Scancode_Z               " },
    { 0x0035, "Qt_Scancode_X               " },
    { 0x0036, "Qt_Scancode_C               " },
    { 0x0037, "Qt_Scancode_V               " },
    { 0x0038, "Qt_Scancode_B               " },
    { 0x0039, "Qt_Scancode_N               " },
    { 0x003a, "Qt_Scancode_M               " },
    { 0x003b, "Qt_Scancode_Comma           " },
    { 0x003c, "Qt_Scancode_Period          " },
    { 0x003d, "Qt_Scancode_Slash           " },
    { 0x0032, "Qt_Scancode_Shift           " },
    { 0x003e, "Qt_Scancode_Shift_Right     " },
    { 0x0025, "Qt_Scancode_Control         " },
    { 0x0069, "Qt_Scancode_Control_Right   " },
};

// KKey2Name::GetNameOfQtScancode: при промахе — пустая строка.
inline std::string GetNameOfQtScancode(int nScancode)
{
    for (const stKeyName& st : g_astQtScancodeName)
        if (st.eKey == nScancode) return st.pszName;
    return "";
}

// g_strKeysym_S40 @0x14e7410 — 233 имён БЕЗ кодов (индекс = позиция).
// В бинарнике-референсе НИКТО эти массивы не читает — мёртвые данные.
inline const char* const g_apszKeysym_S40[233] = {
    "PADK_UNKNOWN",
    "PADK_FIRST",
    "PADK_BACKSPACE",
    "PADK_TAB",
    "PADK_CLEAR",
    "PADK_RETURN",
    "PADK_PAUSE",
    "PADK_ESCAPE",
    "PADK_SPACE",
    "PADK_EXCLAIM",
    "PADK_QUOTEDBL",
    "PADK_HASH",
    "PADK_DOLLAR",
    "PADK_AMPERSAND",
    "PADK_QUOTE",
    "PADK_LEFTPAREN",
    "PADK_RIGHTPAREN",
    "PADK_ASTERISK",
    "PADK_PLUS",
    "PADK_COMMA",
    "PADK_MINUS",
    "PADK_PERIOD",
    "PADK_SLASH",
    "PADK_0",
    "PADK_1",
    "PADK_2",
    "PADK_3",
    "PADK_4",
    "PADK_5",
    "PADK_6",
    "PADK_7",
    "PADK_8",
    "PADK_9",
    "PADK_COLON",
    "PADK_SEMICOLON",
    "PADK_LESS",
    "PADK_EQUALS",
    "PADK_GREATER",
    "PADK_QUESTION",
    "PADK_AT",
    "PADK_LEFTBRACKET",
    "PADK_BACKSLASH",
    "PADK_RIGHTBRACKET",
    "PADK_CARET",
    "PADK_UNDERSCORE",
    "PADK_BACKQUOTE",
    "PADK_a",
    "PADK_b",
    "PADK_c",
    "PADK_d",
    "PADK_e",
    "PADK_f",
    "PADK_g",
    "PADK_h",
    "PADK_i",
    "PADK_j",
    "PADK_k",
    "PADK_l",
    "PADK_m",
    "PADK_n",
    "PADK_o",
    "PADK_p",
    "PADK_q",
    "PADK_r",
    "PADK_s",
    "PADK_t",
    "PADK_u",
    "PADK_v",
    "PADK_w",
    "PADK_x",
    "PADK_y",
    "PADK_z",
    "PADK_DELETE",
    "PADK_WORLD_0",
    "PADK_WORLD_1",
    "PADK_WORLD_2",
    "PADK_WORLD_3",
    "PADK_WORLD_4",
    "PADK_WORLD_5",
    "PADK_WORLD_6",
    "PADK_WORLD_7",
    "PADK_WORLD_8",
    "PADK_WORLD_9",
    "PADK_WORLD_10",
    "PADK_WORLD_11",
    "PADK_WORLD_12",
    "PADK_WORLD_13",
    "PADK_WORLD_14",
    "PADK_WORLD_15",
    "PADK_WORLD_16",
    "PADK_WORLD_17",
    "PADK_WORLD_18",
    "PADK_WORLD_19",
    "PADK_WORLD_20",
    "PADK_WORLD_21",
    "PADK_WORLD_22",
    "PADK_WORLD_23",
    "PADK_WORLD_24",
    "PADK_WORLD_25",
    "PADK_WORLD_26",
    "PADK_WORLD_27",
    "PADK_WORLD_28",
    "PADK_WORLD_29",
    "PADK_WORLD_30",
    "PADK_WORLD_31",
    "PADK_WORLD_32",
    "PADK_WORLD_33",
    "PADK_WORLD_34",
    "PADK_WORLD_35",
    "PADK_WORLD_36",
    "PADK_WORLD_37",
    "PADK_WORLD_38",
    "PADK_WORLD_39",
    "PADK_WORLD_40",
    "PADK_WORLD_41",
    "PADK_WORLD_42",
    "PADK_WORLD_43",
    "PADK_WORLD_44",
    "PADK_WORLD_45",
    "PADK_WORLD_46",
    "PADK_WORLD_47",
    "PADK_WORLD_48",
    "PADK_WORLD_49",
    "PADK_WORLD_50",
    "PADK_WORLD_51",
    "PADK_WORLD_52",
    "PADK_WORLD_53",
    "PADK_WORLD_54",
    "PADK_WORLD_55",
    "PADK_WORLD_56",
    "PADK_WORLD_57",
    "PADK_WORLD_58",
    "PADK_WORLD_59",
    "PADK_WORLD_60",
    "PADK_WORLD_61",
    "PADK_WORLD_62",
    "PADK_WORLD_63",
    "PADK_WORLD_64",
    "PADK_WORLD_65",
    "PADK_WORLD_66",
    "PADK_WORLD_67",
    "PADK_WORLD_68",
    "PADK_WORLD_69",
    "PADK_WORLD_70",
    "PADK_WORLD_71",
    "PADK_WORLD_72",
    "PADK_WORLD_73",
    "PADK_WORLD_74",
    "PADK_WORLD_75",
    "PADK_WORLD_76",
    "PADK_WORLD_77",
    "PADK_WORLD_78",
    "PADK_WORLD_79",
    "PADK_WORLD_80",
    "PADK_WORLD_81",
    "PADK_WORLD_82",
    "PADK_WORLD_83",
    "PADK_WORLD_84",
    "PADK_WORLD_85",
    "PADK_WORLD_86",
    "PADK_WORLD_87",
    "PADK_WORLD_88",
    "PADK_WORLD_89",
    "PADK_WORLD_90",
    "PADK_WORLD_91",
    "PADK_WORLD_92",
    "PADK_WORLD_93",
    "PADK_WORLD_94",
    "PADK_WORLD_95",
    "PADK_KP0",
    "PADK_KP1",
    "PADK_KP2",
    "PADK_KP3",
    "PADK_KP4",
    "PADK_KP5",
    "PADK_KP6",
    "PADK_KP7",
    "PADK_KP8",
    "PADK_KP9",
    "PADK_KP_PERIOD",
    "PADK_KP_DIVIDE",
    "PADK_KP_MULTIPLY",
    "PADK_KP_MINUS",
    "PADK_KP_PLUS",
    "PADK_KP_ENTER",
    "PADK_KP_EQUALS",
    "PADK_UP",
    "PADK_DOWN",
    "PADK_RIGHT",
    "PADK_LEFT",
    "PADK_INSERT",
    "PADK_HOME",
    "PADK_END",
    "PADK_PAGEUP",
    "PADK_PAGEDOWN",
    "PADK_F1",
    "PADK_F2",
    "PADK_F3",
    "PADK_F4",
    "PADK_F5",
    "PADK_F6",
    "PADK_F7",
    "PADK_F8",
    "PADK_F9",
    "PADK_F10",
    "PADK_F11",
    "PADK_F12",
    "PADK_F13",
    "PADK_F14",
    "PADK_F15",
    "PADK_NUMLOCK",
    "PADK_CAPSLOCK",
    "PADK_SCROLLOCK",
    "PADK_RSHIFT",
    "PADK_LSHIFT",
    "PADK_RCTRL",
    "PADK_LCTRL",
    "PADK_RALT",
    "PADK_LALT",
    "PADK_RMETA",
    "PADK_LMETA",
    "PADK_LSUPER",
    "PADK_RSUPER",
    "PADK_MODE",
    "PADK_COMPOSE",
    "PADK_HELP",
    "PADK_PRINT",
    "PADK_SYSREQ",
    "PADK_BREAK",
    "PADK_MENU",
    "PADK_POWER",
    "PADK_EURO",
    "PADK_UNDO",
};

// g_strKeysym_S50 @0x14e9130 — 357 имён БЕЗ кодов (индекс = позиция).
// В бинарнике-референсе НИКТО эти массивы не читает — мёртвые данные.
inline const char* const g_apszKeysym_S50[357] = {
    "SONO_FREEZE",
    "SONO_SaveCine",
    "SONO_Power",
    "SONO_PATDAT",
    "SONO_REPORT",
    "SONO_PROBE",
    "SONO_ENDEXAM",
    "SONO_REVIEW",
    "SONO_P1",
    "SONO_P2",
    "SONO_ELASTRO",
    "SONO_CONSTRAST",
    "SONO_3D4D",
    "SONO_ANGLE_KNOB",
    "SONO_ANGLE",
    "SONO_BodyMark_Knob",
    "SONO_BodyMark",
    "SONO_Clear",
    "SONO_Pointer",
    "SONO_Annot",
    "SONO_Update",
    "SONO_Calc",
    "SONO_Caliper",
    "SONO_Auto",
    "SONO_Print",
    "SONO_VideoPrint",
    "SONO_SaveImage",
    "SONO_Depth_Knob",
    "SONO_Depth",
    "SONO_Zoom_Knob",
    "SONO_Zoom",
    "SONO_Scale_Up",
    "SONO_Scale_Down",
    "SONO_Baseline_Up",
    "SONO_Baseline_Down",
    "SONO_2B",
    "SONO_4B",
    "SONO_B_Mode_Knob",
    "SONO_B_Mode",
    "SONO_CFM_Mode_Knob",
    "SONO_CFM_Mode",
    "SONO_PW_Mode_Knob",
    "SONO_PW_Mode",
    "SONO_CW_Mode_Knob",
    "SONO_CW_Mode",
    "SONO_M_Mode_Knob",
    "SONO_M_Mode",
    "SONO_TouchScreen_Keyboard",
    "SONO_TouchScreen_Knob1",
    "SONO_TouchScreen_Knob2",
    "SONO_TouchScreen_Knob3",
    "SONO_TouchScreen_Knob4",
    "SONO_TouchScreen_Knob5",
    "SONO_Audio_Knob",
    "SONO_Setup",
    "SONO_Help",
    "SONO_P3",
    "SONO_P4",
    "SONO_Biopsy",
    "SONO_Panoramic",
    "SONO_PDI",
    "SONO_TDI",
    "SONO_Updown_Revert",
    "SONO_Leftright_Revert",
    "SONO_THI",
    "SONO_Invert",
    "SONO_PrintScreen",
    "SONO_Del",
    "SONO_QuoteLeft",
    "SONO_1",
    "SONO_2",
    "SONO_3",
    "SONO_4",
    "SONO_5",
    "SONO_6",
    "SONO_7",
    "SONO_8",
    "SONO_9",
    "SONO_0",
    "SONO_Minus",
    "SONO_Equal",
    "SONO_BackSpace",
    "SONO_Tab",
    "SONO_Q",
    "SONO_W",
    "SONO_E",
    "SONO_R",
    "SONO_T",
    "SONO_Y",
    "SONO_U",
    "SONO_I",
    "SONO_O",
    "SONO_P",
    "SONO_BracketLeft",
    "SONO_BracketRight",
    "SONO_BackSlash",
    "SONO_CapsLock",
    "SONO_A",
    "SONO_S",
    "SONO_D",
    "SONO_F",
    "SONO_G",
    "SONO_H",
    "SONO_J",
    "SONO_K",
    "SONO_L",
    "SONO_Semicolon",
    "SONO_QuoteRight",
    "SONO_Enter",
    "SONO_Shift_Left",
    "SONO_Z",
    "SONO_X",
    "SONO_C",
    "SONO_V",
    "SONO_B",
    "SONO_N",
    "SONO_M",
    "SONO_Comma",
    "SONO_Period",
    "SONO_Slash",
    "SONO_UpArrow",
    "SONO_Shift_Right",
    "SONO_Control_Left",
    "SONO_Function",
    "SONO_Arrow",
    "SONO_Alt",
    "SONO_Space",
    "SONO_AltGr",
    "SONO_ScreenZoom",
    "SONO_LeftArrow",
    "SONO_DownArrow",
    "SONO_RightArrow",
    "SONO_Set_Left",
    "SONO_Set_Right",
    "SONO_BackLight_Up",
    "SONO_Volumn_Down",
    "SONO_BackLight_Down",
    "SONO_Volumn_Up",
    "SONO_a",
    "SONO_aacute",
    "SONO_adiaeresis",
    "SONO_ae",
    "SONO_ampersand",
    "SONO_aring",
    "SONO_asciicircum",
    "SONO_asciitilde",
    "SONO_asterisk",
    "SONO_at",
    "SONO_b",
    "SONO_bar",
    "SONO_braceleft",
    "SONO_braceright",
    "SONO_brokenbar",
    "SONO_c",
    "SONO_ccedilla",
    "SONO_cent",
    "SONO_colon",
    "SONO_copyright",
    "SONO_currency",
    "SONO_d",
    "SONO_division",
    "SONO_dollar",
    "SONO_e",
    "SONO_eacute",
    "SONO_eth",
    "SONO_EuroSign",
    "SONO_exclam",
    "SONO_exclamdown",
    "SONO_f",
    "SONO_g",
    "SONO_gbreve",
    "SONO_greater",
    "SONO_h",
    "SONO_i",
    "SONO_iacute",
    "SONO_j",
    "SONO_k",
    "SONO_l",
    "SONO_less",
    "SONO_m",
    "SONO_mu",
    "SONO_multiply",
    "SONO_n",
    "SONO_notsign",
    "SONO_ntilde",
    "SONO_numbersign",
    "SONO_o",
    "SONO_oacute",
    "SONO_odiaeresis",
    "SONO_oe",
    "SONO_onesuperior",
    "SONO_oslash",
    "SONO_p",
    "SONO_paragraph",
    "SONO_parenleft",
    "SONO_parenright",
    "SONO_percent",
    "SONO_plus",
    "SONO_q",
    "SONO_question",
    "SONO_questiondown",
    "SONO_quotedbl",
    "SONO_r",
    "SONO_registered",
    "SONO_s",
    "SONO_scaron",
    "SONO_scedilla",
    "SONO_section",
    "SONO_ssharp",
    "SONO_sterling",
    "SONO_t",
    "SONO_thorn",
    "SONO_threesuperior",
    "SONO_twosuperior",
    "SONO_u",
    "SONO_uacute",
    "SONO_udiaeresis",
    "SONO_underscore",
    "SONO_v",
    "SONO_w",
    "SONO_x",
    "SONO_y",
    "SONO_ydiaeresis",
    "SONO_yen",
    "SONO_z",
    "SONO_zcaron",
    "SONO_Aacute",
    "SONO_Adiaeresis",
    "SONO_AE",
    "SONO_Aring",
    "SONO_Ccedilla",
    "SONO_Eacute",
    "SONO_ETH",
    "SONO_Gbreve",
    "SONO_Iacute",
    "SONO_Ntilde",
    "SONO_Oacute",
    "SONO_Odiaeresis",
    "SONO_OE",
    "SONO_Oslash",
    "SONO_Scaron",
    "SONO_Scedilla",
    "SONO_Thorn",
    "SONO_Uacute",
    "SONO_Udiaeresis",
    "SONO_Ydiaeresis",
    "SONO_Zcaron",
    "SONO_Zoom_Up",
    "SONO_Zoom_Down",
    "SONO_agrave",
    "SONO_acircumflex",
    "SONO_atilde",
    "SONO_Agrave",
    "SONO_Acircumflex",
    "SONO_Atilde",
    "SONO_egrave",
    "SONO_ecircumflex",
    "SONO_etilde",
    "SONO_ediaeresis",
    "SONO_Egrave",
    "SONO_Ecircumflex",
    "SONO_Etilde",
    "SONO_Ediaeresis",
    "SONO_igrave",
    "SONO_icircumflex",
    "SONO_itilde",
    "SONO_idiaeresis",
    "SONO_Igrave",
    "SONO_Icircumflex",
    "SONO_Itilde",
    "SONO_Idiaeresis",
    "SONO_ograve",
    "SONO_ocircumflex",
    "SONO_otilde",
    "SONO_Ograve",
    "SONO_Ocircumflex",
    "SONO_Otilde",
    "SONO_ugrave",
    "SONO_ucircumflex",
    "SONO_utilde",
    "SONO_Ugrave",
    "SONO_Ucircumflex",
    "SONO_Utilde",
    "SONO_uni2035",
    "SONO_minutes",
    "SONO_guillemotleft",
    "SONO_guillemotright",
    "SONO_degree",
    "SONO_FootSwitch_Left",
    "SONO_FootSwitch_Right",
    "SONO_Cyrillic_io",
    "SONO_Cyrillic_IO",
    "SONO_Cyrillic_shorti",
    "SONO_Cyrillic_SHORTI",
    "SONO_Cyrillic_tse",
    "SONO_Cyrillic_TSE",
    "SONO_Cyrillic_u",
    "SONO_Cyrillic_U",
    "SONO_Cyrillic_ka",
    "SONO_Cyrillic_KA",
    "SONO_Cyrillic_ie",
    "SONO_Cyrillic_IE",
    "SONO_Cyrillic_en",
    "SONO_Cyrillic_EN",
    "SONO_Cyrillic_ghe",
    "SONO_Cyrillic_GHE",
    "SONO_Cyrillic_sha",
    "SONO_Cyrillic_SHA",
    "SONO_Cyrillic_shcha",
    "SONO_Cyrillic_SHCHA",
    "SONO_Cyrillic_ze",
    "SONO_Cyrillic_ZE",
    "SONO_Cyrillic_ha",
    "SONO_Cyrillic_HA",
    "SONO_Cyrillic_be",
    "SONO_Cyrillic_BE",
    "SONO_uniFE41",
    "SONO_Cyrillic_ef",
    "SONO_Cyrillic_EF",
    "SONO_Cyrillic_yeru",
    "SONO_Cyrillic_YERU",
    "SONO_Cyrillic_ve",
    "SONO_Cyrillic_VE",
    "SONO_Cyrillic_a",
    "SONO_Cyrillic_A",
    "SONO_Cyrillic_pe",
    "SONO_Cyrillic_PE",
    "SONO_Cyrillic_er",
    "SONO_Cyrillic_ER",
    "SONO_Cyrillic_o",
    "SONO_Cyrillic_O",
    "SONO_Cyrillic_el",
    "SONO_Cyrillic_EL",
    "SONO_Cyrillic_de",
    "SONO_Cyrillic_DE",
    "SONO_Cyrillic_zhe",
    "SONO_Cyrillic_ZHE",
    "SONO_Cyrillic_e",
    "SONO_Cyrillic_E",
    "SONO_Cyrillic_ya",
    "SONO_Cyrillic_YA",
    "SONO_Cyrillic_che",
    "SONO_Cyrillic_CHE",
    "SONO_Cyrillic_es",
    "SONO_Cyrillic_ES",
    "SONO_Cyrillic_em",
    "SONO_Cyrillic_EM",
    "SONO_Cyrillic_i",
    "SONO_Cyrillic_I",
    "SONO_Cyrillic_te",
    "SONO_Cyrillic_TE",
    "SONO_Cyrillic_softsign",
    "SONO_Cyrillic_SOFTSIGN",
    "SONO_Cyrillic_yu",
    "SONO_Cyrillic_YU",
    "SONO_Cyrillic_hardsign",
    "SONO_Cyrillic_HARDSIGN",
};

} // namespace keyname
