// Сгенерировано tools/gen_lcdproxy.py — НЕ РЕДАКТИРОВАТЬ ВРУЧНУЮ.
// Источник: KLcdProxy::m_lcdActTab @0xa4cc88, 1968 байт, 82 записей.

struct _LcdActItem {
    quint16 usKey;
    quint16 usAct;              // 2=press 3=short 4=long 7=set-value
    int (KLcdProxy::*pfnAct)(int);
};

static const _LcdActItem m_lcdActTab[82] = {
    {   0, 3, &KLcdProxy::GainSwitchShortPressAct },
    {   0, 4, &KLcdProxy::GainSwitchLongPressAct },
    {   1, 3, &KLcdProxy::SwitchFreezeStatus },
    {   2, 3, &KLcdProxy::SwitchChbStatus },
    {   2, 4, &KLcdProxy::OpenOrCloseVersionDialog },
    {   3, 4, &KLcdProxy::ResetUserParam },
    {   3, 3, &KLcdProxy::CancelResetUserParam },
    {   4, 3, &KLcdProxy::SwitchImgEnhLevel },
    {   5, 3, &KLcdProxy::SwitchColorEnhLevel },
    {   6, 3, &KLcdProxy::SwitchZoomLevel },
    {   7, 3, &KLcdProxy::SwitchIrisType },
    {   8, 3, &KLcdProxy::SwitchToneMode },
    {   9, 3, &KLcdProxy::ToneAdd },
    {  10, 3, &KLcdProxy::ToneSub },
    {  11, 3, &KLcdProxy::SaveImage },
    {  11, 4, &KLcdProxy::StartOrStopVideoRecord },
    {  12, 3, &KLcdProxy::UnmountUsbDevice },
    {  13, 4, &KLcdProxy::StartWhiteBalance },
    {  14, 3, &KLcdProxy::OpenLamp },
    {  14, 4, &KLcdProxy::CloseLamp },
    {  15, 3, &KLcdProxy::AddLampLevel },
    {  16, 3, &KLcdProxy::SwitchAutoLightAdjust },
    {  17, 3, &KLcdProxy::SwitchManuLightAdjust },
    {  18, 3, &KLcdProxy::StartTrans },
    {  19, 3, &KLcdProxy::SwitchAirPumpLevel },
    {  20, 3, &KLcdProxy::SwitchAirPumpStatus },
    {  21, 3, &KLcdProxy::SwitchVlsMode },
    {  22, 3, &KLcdProxy::SubLampLevel },
    {  23, 3, &KLcdProxy::SwitchContrastType },
    {  24, 7, &KLcdProxy::SwitchOperatingPattern },
    {  25, 3, &KLcdProxy::OpenOrCloseEliminatemoire },
    {  32, 3, &KLcdProxy::ConnectOrDisconnecEndo },
    {  32, 4, &KLcdProxy::PowerOff },
    {  33, 3, &KLcdProxy::OpenOrCloseVersionDialog },
    {  34, 3, &KLcdProxy::OpenOrCloseEndoInfoDialog },
    {  35, 3, &KLcdProxy::SaveImage },
    {  36, 3, &KLcdProxy::StartOrStopVideoRecord },
    {  37, 3, &KLcdProxy::FileView },
    {  38, 3, &KLcdProxy::LockScreenAct },
    { 256, 7, &KLcdProxy::SwitchWindow },
    { 257, 7, &KLcdProxy::SetLanguage },
    { 258, 7, &KLcdProxy::SetTimeFormat },
    { 259, 7, &KLcdProxy::SetVLSGroup },
    { 260, 7, &KLcdProxy::SetConnerShape },
    { 261, 7, &KLcdProxy::SetResolution },
    { 262, 7, &KLcdProxy::SetVideoSplit },
    { 513, 7, &KLcdProxy::SetColorRValue },
    { 514, 7, &KLcdProxy::SetColorBValue },
    { 515, 7, &KLcdProxy::SetColorCValue },
    { 516, 7, &KLcdProxy::SetImgEnhL1Value },
    { 517, 7, &KLcdProxy::SetImgEnhL2Value },
    { 518, 7, &KLcdProxy::SetImgEnhL3Value },
    { 519, 7, &KLcdProxy::SetColorEnhL1Value },
    { 520, 7, &KLcdProxy::SetColorEnhL2Value },
    { 521, 7, &KLcdProxy::SetColorEnhL3Value },
    { 522, 7, &KLcdProxy::SetZoomL1Value },
    { 523, 7, &KLcdProxy::SetZoomL2Value },
    { 524, 7, &KLcdProxy::SetZoomL3Value },
    { 525, 2, &KLcdProxy::RemoteButton0Act },
    { 526, 2, &KLcdProxy::RemoteButton1Act },
    { 527, 2, &KLcdProxy::RemoteButton2Act },
    { 528, 2, &KLcdProxy::RemoteButton3Act },
    { 529, 2, &KLcdProxy::LeftFootSwitchAct },
    { 530, 2, &KLcdProxy::RightFootSwitchAct },
    { 531, 4, &KLcdProxy::RemoteButtonALongPressAct },
    { 532, 3, &KLcdProxy::RemoteButtonAShortPressAct },
    { 533, 4, &KLcdProxy::RemoteButtonBLongPressAct },
    { 534, 3, &KLcdProxy::RemoteButtonBShortPressAct },
    { 535, 4, &KLcdProxy::RemoteButtonMLongPressAct },
    { 536, 3, &KLcdProxy::RemoteButtonMShortPressAct },
    { 525, 7, &KLcdProxy::SetEndoButton0Funcindex },
    { 526, 7, &KLcdProxy::SetEndoButton1Funcindex },
    { 527, 7, &KLcdProxy::SetEndoButton2Funcindex },
    { 528, 7, &KLcdProxy::SetEndoButton3Funcindex },
    { 529, 7, &KLcdProxy::SetLeftFootSwitchFuncindex },
    { 530, 7, &KLcdProxy::SetRightFootSwitchFuncindex },
    { 531, 7, &KLcdProxy::SetCameraButtomALongPressFuncIndex },
    { 532, 7, &KLcdProxy::SetCameraButtomAShortPressFuncIndex },
    { 533, 7, &KLcdProxy::SetCameraButtomBLongPressFuncIndex },
    { 534, 7, &KLcdProxy::SetCameraButtomBShortPressFuncIndex },
    { 535, 7, &KLcdProxy::SetCameraButtomMLongPressFuncIndex },
    { 536, 7, &KLcdProxy::SetCameraButtomMShortPressFuncIndex },
};
